config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  resources :engines
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/engine.rb
class Engine < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :set_engine, only: [:show, :edit, :update, :destroy]

  # GET /engines
  # GET /engines.json
  def index
    @engines = Engine.all
  end

  # GET /engines/1
  # GET /engines/1.json
  def show
  end

  # GET /engines/new
  def new
    @engine = Engine.new
  end

  # GET /engines/1/edit
  def edit
  end

  # POST /engines
  # POST /engines.json
  def create
    @engine = Engine.new(engine_params)

    respond_to do |format|
      if @engine.save
        format.html { redirect_to @engine, notice: 'Engine was successfully created.' }
        format.json { render :show, status: :created, location: @engine }
      else
        format.html { render :new }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engines/1
  # PATCH/PUT /engines/1.json
  def update
    respond_to do |format|
      if @engine.update(engine_params)
        format.html { redirect_to @engine, notice: 'Engine was successfully updated.' }
        format.json { render :show, status: :ok, location: @engine }
      else
        format.html { render :edit }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1
  # DELETE /engines/1.json
  def destroy
    @engine.destroy
    respond_to do |format|
      format.html { redirect_to engines_url, notice: 'Engine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engine
      @engine = Engine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def engine_params
      params.require(:engine).permit(:mass, :max_torque, :max_hp, :max_rpm)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:name, :drag_c, :drag_area, :friction_c_ground, :friction_c_trans, :mass, :wheel_diameter, :gear_ratio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/engines/_form.html.erb
<%= form_with(model: engine) do |form| %>
  <% if engine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(engine.errors.count, "error") %> prohibited this engine from being saved:</h2>

      <ul>
        <% engine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mass %>
    <%= form.text_field :mass %>
  </div>

  <div class="field">
    <%= form.label :max_torque %>
    <%= form.text_field :max_torque %>
  </div>

  <div class="field">
    <%= form.label :max_hp %>
    <%= form.text_field :max_hp %>
  </div>

  <div class="field">
    <%= form.label :max_rpm %>
    <%= form.text_field :max_rpm %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/engines/edit.html.erb
<h1>Editing Engine</h1>

<%= render 'form', engine: @engine %>

<%= link_to 'Show', @engine %> |
<%= link_to 'Back', engines_path %>

app/views/engines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Engines</h1>

<table>
  <thead>
    <tr>
      <th>Mass</th>
      <th>Max torque</th>
      <th>Max hp</th>
      <th>Max rpm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @engines.each do |engine| %>
      <tr>
        <td><%= engine.mass %></td>
        <td><%= engine.max_torque %></td>
        <td><%= engine.max_hp %></td>
        <td><%= engine.max_rpm %></td>
        <td><%= link_to 'Show', engine %></td>
        <td><%= link_to 'Edit', edit_engine_path(engine) %></td>
        <td><%= link_to 'Destroy', engine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Engine', new_engine_path %>

app/views/engines/new.html.erb
<h1>New Engine</h1>

<%= render 'form', engine: @engine %>

<%= link_to 'Back', engines_path %>

app/views/engines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mass:</strong>
  <%= @engine.mass %>
</p>

<p>
  <strong>Max torque:</strong>
  <%= @engine.max_torque %>
</p>

<p>
  <strong>Max hp:</strong>
  <%= @engine.max_hp %>
</p>

<p>
  <strong>Max rpm:</strong>
  <%= @engine.max_rpm %>
</p>

<%= link_to 'Edit', edit_engine_path(@engine) %> |
<%= link_to 'Back', engines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newton</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :drag_c %>
    <%= form.text_field :drag_c %>
  </div>

  <div class="field">
    <%= form.label :drag_area %>
    <%= form.text_field :drag_area %>
  </div>

  <div class="field">
    <%= form.label :friction_c_ground %>
    <%= form.text_field :friction_c_ground %>
  </div>

  <div class="field">
    <%= form.label :friction_c_trans %>
    <%= form.text_field :friction_c_trans %>
  </div>

  <div class="field">
    <%= form.label :mass %>
    <%= form.text_field :mass %>
  </div>

  <div class="field">
    <%= form.label :wheel_diameter %>
    <%= form.text_field :wheel_diameter %>
  </div>

  <div class="field">
    <%= form.label :gear_ratio %>
    <%= form.text_field :gear_ratio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Drag c</th>
      <th>Drag area</th>
      <th>Friction c ground</th>
      <th>Friction c trans</th>
      <th>Mass</th>
      <th>Wheel diameter</th>
      <th>Gear ratio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.name %></td>
        <td><%= vehicle.drag_c %></td>
        <td><%= vehicle.drag_area %></td>
        <td><%= vehicle.friction_c_ground %></td>
        <td><%= vehicle.friction_c_trans %></td>
        <td><%= vehicle.mass %></td>
        <td><%= vehicle.wheel_diameter %></td>
        <td><%= vehicle.gear_ratio %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vehicle.name %>
</p>

<p>
  <strong>Drag c:</strong>
  <%= @vehicle.drag_c %>
</p>

<p>
  <strong>Drag area:</strong>
  <%= @vehicle.drag_area %>
</p>

<p>
  <strong>Friction c ground:</strong>
  <%= @vehicle.friction_c_ground %>
</p>

<p>
  <strong>Friction c trans:</strong>
  <%= @vehicle.friction_c_trans %>
</p>

<p>
  <strong>Mass:</strong>
  <%= @vehicle.mass %>
</p>

<p>
  <strong>Wheel diameter:</strong>
  <%= @vehicle.wheel_diameter %>
</p>

<p>
  <strong>Gear ratio:</strong>
  <%= @vehicle.gear_ratio %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>